import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Result from '../components/Result'
import requests from '../utils/requests'

export default function Home({ results }) {
  

  return (
    <div>
      <Head>
        <title>World Movie - Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header></Header>
      {/* Navigation */}
      <Nav/>

      {/* Result */}
      <Result movie={results} />
    </div>
  )
}


export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const url = `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`;

  const request = await fetch(url).then((res => res.json()));
  
  return {
    props: {
      results: request
    }
  }


}